version: '3.8'

services:
  database-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=obra-facil

  redis:
    image: redis:latest
    command: redis-server --requirepass redispwd
    ports:
      - 6379:6379
