name: Build and test any branch except main and develop

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!develop'

jobs:
  test:
    strategy:
      matrix:
        node-version: ['20.12.2']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run tests
      run: echo "// TODO add npm test \\"

  build:
    strategy:
      matrix:
        node-version: ['20.12.2']
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build